name: Release

on:
  workflow_dispatch:
  push:

jobs:
  packaging-debian:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential devscripts dh-make dh-dkms dkms
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: as21xxx-dkms
    - name: Packaging
      working-directory: as21xxx-dkms
      run: |
        LATEST_VERSION=$(grep "^PACKAGE_VERSION" "dkms.conf" | sed 's/.*\?"\([^"]*\)".*/\1/')
        sed -i "s/###LATEST_VERSION###/$LATEST_VERSION/g" debian/control debian/changelog
        dpkg-buildpackage -b -tc -us -uc
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: debain-package
        path: "*.deb"

  release:
    runs-on: ubuntu-24.04-arm
    needs: [packaging-debian]
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        path: as21xxx-dkms
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: Create Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.deb